### ISSUE TITLE
JavaScriptでUnicode表記が2バイトまでしかできない

### ISSUE THREAD

**Issue by cognitom** [aozorahack/aozora-parser.js#3]
ひとまず、[2バイトまでで追加しました](https://github.com/cognitom/aozora-parser.js/blob/99a141b3de9a007d0141decab984756a58173045/aozora-parser.pegjs#L25)が、3バイト以上の漢字をどうしよう問題。ES6だと解決するらしい?
https://mathiasbynens.be/notes/javascript-unicode

**Comment by takahashim** [comment]
青空文庫の現在の仕様に沿った形にするのであれば、2バイトまでで十分というか、そうではない文字はJIS X 0208+0213外の文字になるため、注記記法で記入することになるんではないかと。

**Comment by cognitom** [comment]
なるほど、であればこのままでも良いのかも。
Issueは一旦クローズしますね。必要が出てきたらまた。
